<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DataDrivenDemo</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>93c01910-8bea-467c-b401-279fb73a40c4</testSuiteGuid>
   <testCaseLink>
      <guid>74823b7c-9487-42d9-aff3-9792563ca1e8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Demo/DataDrivenTestingDemo</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>063f4ced-b9c2-4d24-b42b-c741fd9aac06</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/LoginData</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>063f4ced-b9c2-4d24-b42b-c741fd9aac06</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>83df2915-50b5-4465-841f-cbcd829dbd94</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>063f4ced-b9c2-4d24-b42b-c741fd9aac06</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>fa43d71a-73c6-4d1a-8d1b-6244280087b9</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
